=== kasheylm/qa_cm_1.0/target/test-classes/dbunit-dataset.dtd
<!ELEMENT dataset (
    ACTION_CONFIG*,
    ACTION_CONFIG_DETAIL*,
    ACTION_RESULT*,
    ACTION_SET*,
    ACTIVITY*,
    ACTIVITY_FILTER*,
    ACTIVITY_FREQUENCY*,
    ACTIVITY_PROPERTY*,
    ACTIVITY_TARGET_GROUP*,
    ACTIVITY_TARGET_GROUP_DETAILS*,
    CAMPAIGN*,
    CONDITION*,
    CONDITION_GROUP*,
    CONDITION_SET*,
    CONDITION_VALUE*,
    COUNTRY*,
    COUNTY*,
    CRON_EXPRESSION*,
    EPS_CONDITION*,
    EPS_CONDITION_RESULT*,
    EPS_CONDITION_SET*,
    EXCLUSION_DATE*,
    LANGUAGE*,
    LVALUE*,
    OPERATOR*,
    PLAYER_DISTRIBUTION*,
    TAG*,
    VALUE_DESCRIPTOR*,
    VALUE_GROUP*,
    VALUE_INPUT_TYPE*,
    VALUE_PROVIDER*,
    VALUE_VALIDATOR*)>

<!ELEMENT ACTION_CONFIG EMPTY>
<!ATTLIST ACTION_CONFIG
    ACTION_CONFIG_ID CDATA #REQUIRED
    ACTION_ORDER CDATA #IMPLIED
    BEAN_NAME CDATA #IMPLIED
    NAME CDATA #REQUIRED
    ACTION_TYPE CDATA #REQUIRED
    ACTION_SET_ID CDATA #REQUIRED
    LABEL CDATA #IMPLIED
>

<!ELEMENT ACTION_CONFIG_DETAIL EMPTY>
<!ATTLIST ACTION_CONFIG_DETAIL
    ACTION_CONFIG_DETAIL_ID CDATA #REQUIRED
    CONFIG_KEY CDATA #REQUIRED
    CONFIG_VALUE CDATA #IMPLIED
    ACTION_CONFIG_ID CDATA #IMPLIED
    DYNAMIC CDATA #REQUIRED
>

<!ELEMENT ACTION_RESULT EMPTY>
<!ATTLIST ACTION_RESULT
    ACTION_RESULT_ID CDATA #REQUIRED
    ACTION_STATUS CDATA #IMPLIED
    END_DATE CDATA #IMPLIED
    START_DATE CDATA #REQUIRED
    ACTION_CONFIG_ID CDATA #REQUIRED
    ACTIVITY_ID CDATA #REQUIRED
    CAMPAIGN_ID CDATA #IMPLIED
    TARGET_GROUP_ID CDATA #REQUIRED
    PLAYER_NAME CDATA #IMPLIED
    CASINO_NAME CDATA #IMPLIED
    ACTION_SET_INVOCATION_ID CDATA #REQUIRED
>

<!ELEMENT ACTION_SET EMPTY>
<!ATTLIST ACTION_SET
    ACTION_SET_ID CDATA #REQUIRED
>

<!ELEMENT ACTIVITY EMPTY>
<!ATTLIST ACTIVITY
    ACTIVITY_ID CDATA #REQUIRED
    APPROVED_BY CDATA #IMPLIED
    APPROVED_DATE CDATA #IMPLIED
    CREATED_BY CDATA #IMPLIED
    CREATED_DATE CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    END_DATE CDATA #IMPLIED
    LABEL CDATA #IMPLIED
    NAME CDATA #REQUIRED
    OPT_IN CDATA #REQUIRED
    PUBLICATION_DATE CDATA #IMPLIED
    START_DATE CDATA #REQUIRED
    STATUS_NAME CDATA #REQUIRED
    TEST CDATA #REQUIRED
    UPDATED_BY CDATA #IMPLIED
    UPDATED_DATE CDATA #IMPLIED
    CAMPAIGN_ID CDATA #IMPLIED
    CASINO_ID CDATA #IMPLIED
    CASINO_NAME CDATA #IMPLIED
    ACTIVITY_FILTER_ID CDATA #IMPLIED
>

<!ELEMENT ACTIVITY_FILTER EMPTY>
<!ATTLIST ACTIVITY_FILTER
    TYPE CDATA #REQUIRED
    ACTIVITY_FILTER_ID CDATA #REQUIRED
    DESCRIPTION CDATA #REQUIRED
    NAME CDATA #REQUIRED
    EVENT_TYPE CDATA #IMPLIED
    CASINO CDATA #IMPLIED
    CLIENT_TYPE CDATA #IMPLIED
    PLATFORM CDATA #IMPLIED
    START_DATE CDATA #IMPLIED
    LANGUAGE_ID CDATA #IMPLIED
>

<!ELEMENT ACTIVITY_FREQUENCY EMPTY>
<!ATTLIST ACTIVITY_FREQUENCY
    ACTIVITY_FREQUENCY_ID CDATA #REQUIRED
    MAX_TIMES CDATA #REQUIRED
    PERIOD_QUALIFIER CDATA #IMPLIED
    TIMEUNIT CDATA #REQUIRED
    TIMEUNIT_NUMBER CDATA #REQUIRED
    WEEKDAYS_MAP CDATA #REQUIRED
    ACTIVITY_ID CDATA #REQUIRED
>

<!ELEMENT ACTIVITY_PROPERTY EMPTY>
<!ATTLIST ACTIVITY_PROPERTY
    ACTIVITY_ID CDATA #REQUIRED
    VALUE CDATA #IMPLIED
    KEY CDATA #REQUIRED
>

<!ELEMENT ACTIVITY_TARGET_GROUP EMPTY>
<!ATTLIST ACTIVITY_TARGET_GROUP
    ACTIVITY_TARGET_GROUP_ID CDATA #REQUIRED
    CONTROL CDATA #REQUIRED
    NAME CDATA #REQUIRED
    PERCENT CDATA #REQUIRED
    ACTION_SET_ID CDATA #IMPLIED
    ACTIVITY_ID CDATA #IMPLIED
    LABEL CDATA #IMPLIED
>

<!ELEMENT ACTIVITY_TARGET_GROUP_DETAILS EMPTY>
<!ATTLIST ACTIVITY_TARGET_GROUP_DETAILS
    ATG_DETAILS_ID CDATA #REQUIRED
    ACTIVITY_TARGET_GROUP_ID CDATA #REQUIRED
    UNIQUE_PLAYERS_ACTIONED CDATA #REQUIRED
>

<!ELEMENT CAMPAIGN EMPTY>
<!ATTLIST CAMPAIGN
    CAMPAIGN_ID CDATA #REQUIRED
    APPROVED_BY CDATA #IMPLIED
    APPROVED_DATE CDATA #IMPLIED
    CATEGORY_ID CDATA #REQUIRED
    CREATED_BY CDATA #IMPLIED
    CREATED_DATE CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    END_DATE CDATA #IMPLIED
    LABEL CDATA #REQUIRED
    LINKS CDATA #IMPLIED
    NAME CDATA #REQUIRED
    PUBLICATION_DATE CDATA #IMPLIED
    START_DATE CDATA #IMPLIED
    STATUS_NAME CDATA #REQUIRED
    UPDATED_BY CDATA #IMPLIED
    UPDATED_DATE CDATA #IMPLIED
    DERIVED_DATES CDATA #IMPLIED
    CASINO_ID CDATA #IMPLIED
    CASINO_NAME CDATA #IMPLIED
>

<!ELEMENT CONDITION EMPTY>
<!ATTLIST CONDITION
    CONDITION_ID CDATA #REQUIRED
    EXPRESSION CDATA #IMPLIED
    NAME CDATA #IMPLIED
    STORE_STATE CDATA #REQUIRED
    WEIGHT CDATA #REQUIRED
    CONDITION_GROUP_ID CDATA #REQUIRED
    LVALUE CDATA #IMPLIED
    OPERATOR_GROUP CDATA #IMPLIED
    OPERATOR CDATA #IMPLIED
    LABEL CDATA #REQUIRED
>

<!ELEMENT CONDITION_GROUP EMPTY>
<!ATTLIST CONDITION_GROUP
    CONDITION_GROUP_ID CDATA #REQUIRED
    NAME CDATA #IMPLIED
    CONDITION_SET_ID CDATA #REQUIRED
    LABEL CDATA #REQUIRED
    TYPE CDATA #REQUIRED
    DESCRIPTION CDATA #IMPLIED
>

<!ELEMENT CONDITION_SET EMPTY>
<!ATTLIST CONDITION_SET
    CONDITION_SET_ID CDATA #REQUIRED
    NAME CDATA #IMPLIED
    ACTIVITY_ID CDATA #IMPLIED
    LABEL CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
>

<!ELEMENT CONDITION_VALUE EMPTY>
<!ATTLIST CONDITION_VALUE
    CONDITION_ID CDATA #IMPLIED
    VALUE CDATA #IMPLIED
    IDX CDATA #IMPLIED
>

<!ELEMENT COUNTRY EMPTY>
<!ATTLIST COUNTRY
    COUNTRY_ID CDATA #REQUIRED
    CODE CDATA #REQUIRED
    COUNTRY_NAME CDATA #REQUIRED
>

<!ELEMENT COUNTY EMPTY>
<!ATTLIST COUNTY
    COUNTY_ID CDATA #REQUIRED
    CODE CDATA #REQUIRED
    COUNTY_NAME CDATA #REQUIRED
    COUNTRY_ID CDATA #IMPLIED
>

<!ELEMENT CRON_EXPRESSION EMPTY>
<!ATTLIST CRON_EXPRESSION
    ACTIVITY_FILTER_ID CDATA #REQUIRED
    CRON_EXPRESSION CDATA #REQUIRED
    IDX CDATA #REQUIRED
>

<!ELEMENT EPS_CONDITION EMPTY>
<!ATTLIST EPS_CONDITION
    ID CDATA #REQUIRED
    CONDITION_SET_ID CDATA #REQUIRED
    EXPRESSION CDATA #REQUIRED
    HAS_STATE CDATA #REQUIRED
    TRIGGER_TYPE CDATA #IMPLIED
>

<!ELEMENT EPS_CONDITION_RESULT EMPTY>
<!ATTLIST EPS_CONDITION_RESULT
    ID CDATA #REQUIRED
    CONDITION_ID CDATA #REQUIRED
    PLAYER_NAME CDATA #REQUIRED
    CASINO_NAME CDATA #REQUIRED
    EVALUATION_DATE CDATA #REQUIRED
>

<!ELEMENT EPS_CONDITION_SET EMPTY>
<!ATTLIST EPS_CONDITION_SET
    ID CDATA #REQUIRED
    LABEL CDATA #REQUIRED
    START_DATE CDATA #REQUIRED
    END_DATE CDATA #IMPLIED
    DESTINATION CDATA #REQUIRED
    REPLY_TO CDATA #REQUIRED
    ACTIVE CDATA #REQUIRED
    EXPLICIT_LABEL CDATA #IMPLIED
    CASINO_NAME CDATA #REQUIRED
>

<!ELEMENT EXCLUSION_DATE EMPTY>
<!ATTLIST EXCLUSION_DATE
    ACTIVITY_FILTER_ID CDATA #REQUIRED
    EXCLUSION_DATE CDATA #IMPLIED
    IDX CDATA #IMPLIED
>

<!ELEMENT LANGUAGE EMPTY>
<!ATTLIST LANGUAGE
    LANGUAGE_ID CDATA #REQUIRED
    CODE CDATA #REQUIRED
    NAME CDATA #REQUIRED
>

<!ELEMENT LVALUE EMPTY>
<!ATTLIST LVALUE
    LVALUE_ID CDATA #REQUIRED
    ALLOW_ADD CDATA #REQUIRED
    ALLOW_DELETE CDATA #REQUIRED
    DEFAULT_POSITION CDATA #IMPLIED
    DEFAULT_VALUE CDATA #IMPLIED
    DESCRIPTION CDATA #IMPLIED
    EXPRESSION CDATA #REQUIRED
    FROM_VALUE_PROVIDER_ONLY CDATA #REQUIRED
    MAIN_CONDITION CDATA #REQUIRED
    MESSAGE_TEMPLATE CDATA #REQUIRED
    NAME CDATA #REQUIRED
    WEIGHT CDATA #REQUIRED
    VALUE_DESCRIPTOR_ID CDATA #REQUIRED
    VALUE_GROUP_ID CDATA #IMPLIED
>

<!ELEMENT OPERATOR EMPTY>
<!ATTLIST OPERATOR
    OPERATOR_ID CDATA #REQUIRED
    EXPRESSION CDATA #REQUIRED
    NAME CDATA #REQUIRED
    RVALUE_INPUT_TYPE_ID CDATA #IMPLIED
    VALUE_DESCRIPTOR_ID CDATA #IMPLIED
>

<!ELEMENT PLAYER_DISTRIBUTION EMPTY>
<!ATTLIST PLAYER_DISTRIBUTION
    PLAYER_DISTRIBUTION_ID CDATA #REQUIRED
    ACTIVITY_TARGET_GROUP_ID CDATA #REQUIRED
    PLAYER_NAME CDATA #IMPLIED
    CASINO_NAME CDATA #IMPLIED
    DISTRIBUTION_DATE CDATA #IMPLIED
>

<!ELEMENT TAG EMPTY>
<!ATTLIST TAG
    TAG_ID CDATA #REQUIRED
    VALUE CDATA #REQUIRED
    CAMPAIGN_ID CDATA #REQUIRED
>

<!ELEMENT VALUE_DESCRIPTOR EMPTY>
<!ATTLIST VALUE_DESCRIPTOR
    VALUE_DESCRIPTOR_ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
    TYPE CDATA #REQUIRED
>

<!ELEMENT VALUE_GROUP EMPTY>
<!ATTLIST VALUE_GROUP
    VALUE_GROUP_ID CDATA #REQUIRED
    NAME CDATA #REQUIRED
>

<!ELEMENT VALUE_INPUT_TYPE EMPTY>
<!ATTLIST VALUE_INPUT_TYPE
    VALUE_INPUT_TYPE_ID CDATA #REQUIRED
    INPUT_TYPE CDATA #REQUIRED
>

<!ELEMENT VALUE_PROVIDER EMPTY>
<!ATTLIST VALUE_PROVIDER
    VALUE_PROVIDER_ID CDATA #REQUIRED
    EXPRESSION CDATA #REQUIRED
    NAME CDATA #REQUIRED
    LVALUE_ID CDATA #IMPLIED
>

<!ELEMENT VALUE_VALIDATOR EMPTY>
<!ATTLIST VALUE_VALIDATOR
    VALUE_VALIDATOR_ID CDATA #REQUIRED
    FAIL_MESSAGE_TEMPLATE CDATA #REQUIRED
    REGEXP CDATA #REQUIRED
    LVALUE_ID CDATA #IMPLIED
>

=== kasheylm/qa_cm_1.0/src/test/resources/search/SearchByCategoryTest.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "dbunit-dataset.dtd">
<dataset>
    <CAMPAIGN
            CAMPAIGN_ID="10001"
            DERIVED_DATES="0"
            APPROVED_BY="tumakha"
            APPROVED_DATE="2012-01-01 11:06:41.114000000"
            CASINO_NAME="playtech81004"
            CASINO_ID="81004"
            CATEGORY_ID="ACQUISITION"
            CREATED_BY="dedr"
            CREATED_DATE="2012-01-01 11:06:41.114000000"
            DESCRIPTION="In design status"
            END_DATE="2010-01-01 11:06:41"
            LABEL="camp.1"
            LINKS="http://www.sometest.kiev.ua"
            NAME="In Design"
            PUBLICATION_DATE="2012-01-01 11:06:41.114000000"
            START_DATE="2010-01-01 11:06:41"
            STATUS_NAME="IN_DESIGN"
            UPDATED_BY="zxczxc"
            UPDATED_DATE="2012-01-01 11:06:41.114000000"
            />
    <ACTIVITY
            ACTIVITY_ID="20001"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="eb12ee5b-e96f-4347-8f03-23b3fb391a30"
            NAME="Activity 1"
            OPT_IN="0"
            PUBLICATION_DATE="2012-08-29 13:41:00.0"
            START_DATE="2012-08-29 13:41:00.0"
            STATUS_NAME="IN_DESIGN"
            TEST="0"
            CAMPAIGN_ID="10001"
            />
    <CAMPAIGN
            CAMPAIGN_ID="10002"
            DERIVED_DATES="0"
            APPROVED_BY="tumakha"
            APPROVED_DATE="2012-01-01 11:06:41.114000000"
            CASINO_NAME="playtech81004"
            CASINO_ID="81004"
            CATEGORY_ID="RETENTION"
            CREATED_BY="tumakha"
            CREATED_DATE="2012-01-01 11:06:41.114000000"
            DESCRIPTION="Approved status"
            END_DATE="2020-01-01 11:06:41"
            LABEL="camp.2"
            LINKS="links"
            NAME="Approved"
            PUBLICATION_DATE="2012-01-01 11:06:41.114000000"
            START_DATE="2015-01-01 11:06:41"
            STATUS_NAME="APPROVED"
            UPDATED_BY="zxczxc"
            UPDATED_DATE="2012-01-01 11:06:41.114000000"
            />
    <ACTIVITY
            ACTIVITY_ID="20002"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="eb12ee5b-e96f-4347-8f03-23b3fb391a30"
            NAME="Activity 1"
            OPT_IN="0"
            PUBLICATION_DATE="2012-08-29 13:41:00.0"
            START_DATE="2012-08-29 13:41:00.0"
            STATUS_NAME="IN_DESIGN"
            TEST="0"
            CAMPAIGN_ID="10002"
            />
    <CAMPAIGN
            CAMPAIGN_ID="10003"
            DERIVED_DATES="0"
            APPROVED_BY="tumakha"
            APPROVED_DATE="2012-01-01 11:06:41.114000000"
            CASINO_ID="81004"
            CASINO_NAME="playtech81004"
            CATEGORY_ID="CONVERSION"
            CREATED_BY="tumakha"
            CREATED_DATE="2012-01-01 11:06:41.114000000"
            DESCRIPTION="Active status"
            END_DATE="2020-01-01 11:06:41"
            LABEL="camp.3"
            LINKS="links"
            NAME="Active"
            PUBLICATION_DATE="2012-01-01 11:06:41.114000000"
            START_DATE="2010-01-01 11:06:41"
            STATUS_NAME="ACTIVE"
            UPDATED_BY="zxczxc"
            UPDATED_DATE="2012-01-01 11:06:41.114000000"
            />
    <ACTIVITY
            ACTIVITY_ID="20003"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="eb12ee5b-e96f-4347-8f03-23b3fb391a30"
            NAME="Activity 1"
            OPT_IN="0"
            PUBLICATION_DATE="2012-08-29 13:41:00.0"
            START_DATE="2012-08-29 13:41:00.0"
            STATUS_NAME="IN_DESIGN"
            TEST="0"
            CAMPAIGN_ID="10003"
            />
    <CAMPAIGN
            CAMPAIGN_ID="10004"
            DERIVED_DATES="0"
            APPROVED_BY="tumakha"
            APPROVED_DATE="2012-01-01 11:06:41.114000000"
            CASINO_ID="81004"
            CASINO_NAME="playtech81004"
            CATEGORY_ID="CROSS_MARKETING"
            CREATED_BY="tumakha"
            CREATED_DATE="2012-01-01 11:06:41.114000000"
            DESCRIPTION="Completed"
            END_DATE="2010-01-01 11:06:41"
            LABEL="camp.4"
            LINKS="links"
            NAME="Completed"
            PUBLICATION_DATE="2012-01-01 11:06:41.114000000"
            START_DATE="2009-01-01 11:06:41"
            STATUS_NAME="COMPLETED"
            UPDATED_BY="zxczxc"
            UPDATED_DATE="2012-01-01 11:06:41.114000000"
            />
    <ACTIVITY
            ACTIVITY_ID="20004"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="eb12ee5b-e96f-4347-8f03-23b3fb391a30"
            NAME="Activity 1"
            OPT_IN="0"
            PUBLICATION_DATE="2012-08-29 13:41:00.0"
            START_DATE="2012-08-29 13:41:00.0"
            STATUS_NAME="IN_DESIGN"
            TEST="0"
            CAMPAIGN_ID="10004"
            />
    <CAMPAIGN
            CAMPAIGN_ID="10005"
            DERIVED_DATES="0"
            APPROVED_BY="tumakha"
            APPROVED_DATE="2012-01-01 11:06:41.114000000"
            CASINO_ID="81004"
            CASINO_NAME="playtech81004"
            CATEGORY_ID="REACTIVATION"
            CREATED_BY="tumakha"
            CREATED_DATE="2012-01-01 11:06:41.114000000"
            DESCRIPTION="Disabled"
            END_DATE="2018-01-01 11:06:41"
            LABEL="camp.5"
            LINKS="links"
            NAME="Disabled"
            PUBLICATION_DATE="2012-01-01 11:06:41.114000000"
            START_DATE="2015-01-01 11:06:41"
            STATUS_NAME="DISABLED"
            UPDATED_BY="zxczxc"
            UPDATED_DATE="2012-01-01 11:06:41.114000000"
            />
    <ACTIVITY
            ACTIVITY_ID="20005"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="eb12ee5b-e96f-4347-8f03-23b3fb391a30"
            NAME="Activity 1"
            OPT_IN="0"
            PUBLICATION_DATE="2012-08-29 13:41:00.0"
            START_DATE="2012-08-29 13:41:00.0"
            STATUS_NAME="IN_DESIGN"
            TEST="0"
            CAMPAIGN_ID="10005"
            />
</dataset>

=== kasheylm/qa_cm_1.0/src/test/resources/search/SearchByStatusTest.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "dbunit-dataset.dtd">
<dataset>
    <CAMPAIGN
            CAMPAIGN_ID="10001"
            CASINO_ID="81004"
            CASINO_NAME="playtech81004"
            CATEGORY_ID="ACQUISITION"
            CREATED_BY="Denys_M"
            CREATED_DATE="2012-09-05 17:55:19.776"
            DERIVED_DATES="0"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="cmp1"
            NAME="In Design"
            PUBLICATION_DATE="2010-01-01 11:06:00.0"
            START_DATE="2010-01-01 11:06:00.0"
            STATUS_NAME="IN_DESIGN"
            UPDATED_BY="Denys_M"
            UPDATED_DATE="2012-09-05 17:59:04.818"
            />
    <ACTIVITY
            ACTIVITY_ID="11001"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="eb12ee5b-e96f-4347-8f03-23b3fb391a30"
            NAME="Activity 1"
            OPT_IN="0"
            PUBLICATION_DATE="2010-01-01 11:06:00.0"
            START_DATE="2010-01-01 11:06:00.0"
            STATUS_NAME="IN_DESIGN"
            TEST="0"
            CAMPAIGN_ID="10001"
            />
    <CAMPAIGN
            CAMPAIGN_ID="10002"
            CASINO_ID="81004"
            CASINO_NAME="playtech81004"
            CATEGORY_ID="ACQUISITION"
            CREATED_BY="Denys_M"
            CREATED_DATE="2012-09-05 17:55:19.776"
            DERIVED_DATES="0"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="cmp2"
            NAME="Approved"
            PUBLICATION_DATE="2010-01-01 11:06:00.0"
            START_DATE="2019-02-04 01:00:00.0"
            STATUS_NAME="APPROVED"
            UPDATED_BY="Denys_M"
            UPDATED_DATE="2012-09-05 17:59:04.818"
            />
    <ACTIVITY
            ACTIVITY_ID="11002"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="eb12ee5b-e96f-4347-8f03-23b3fb391a30"
            NAME="Activity 1"
            OPT_IN="0"
            PUBLICATION_DATE="2010-01-01 11:06:00.0"
            START_DATE="2019-02-04 01:00:00.0"
            STATUS_NAME="APPROVED"
            TEST="0"
            CAMPAIGN_ID="10002"
            />
    <CAMPAIGN
            CAMPAIGN_ID="10003"
            CASINO_ID="81004"
            CASINO_NAME="playtech81004"
            CATEGORY_ID="ACQUISITION"
            CREATED_BY="Denys_M"
            CREATED_DATE="2012-09-05 17:55:19.776"
            DERIVED_DATES="0"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="cmp3"
            NAME="Active"
            PUBLICATION_DATE="2010-01-01 11:06:00.0"
            START_DATE="2010-01-01 11:06:00.0"
            STATUS_NAME="ACTIVE"
            UPDATED_BY="Denys_M"
            UPDATED_DATE="2012-09-05 17:59:04.818"
            />
    <ACTIVITY
            ACTIVITY_ID="11003"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="eb12ee5b-e96f-4347-8f03-23b3fb391a30"
            NAME="Activity 1"
            OPT_IN="0"
            PUBLICATION_DATE="2010-01-01 11:06:00.0"
            START_DATE="2010-01-01 11:06:00.0"
            STATUS_NAME="ACTIVE"
            TEST="0"
            CAMPAIGN_ID="10003"
            />

    <CAMPAIGN
            CAMPAIGN_ID="10004"
            CASINO_ID="81004"
            CASINO_NAME="playtech81004"
            CATEGORY_ID="ACQUISITION"
            CREATED_BY="Denys_M"
            CREATED_DATE="2012-09-05 17:55:19.776"
            DERIVED_DATES="0"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="cmp4"
            NAME="Completed"
            PUBLICATION_DATE="2010-01-01 11:06:00.0"
            START_DATE="2019-02-04 01:00:00.0"
            STATUS_NAME="COMPLETED"
            UPDATED_BY="Denys_M"
            UPDATED_DATE="2012-09-05 17:59:04.818"
            />
    <ACTIVITY
            ACTIVITY_ID="11004"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="eb12ee5b-e96f-4347-8f03-23b3fb391a30"
            NAME="Activity 1"
            OPT_IN="0"
            PUBLICATION_DATE="2010-01-01 11:06:00.0"
            START_DATE="2019-02-04 01:00:00.0"
            STATUS_NAME="COMPLETED"
            TEST="0"
            CAMPAIGN_ID="10004"
            />
    <CAMPAIGN
            CAMPAIGN_ID="10005"
            CASINO_ID="81004"
            CASINO_NAME="playtech81004"
            CATEGORY_ID="ACQUISITION"
            CREATED_BY="Denys_M"
            CREATED_DATE="2012-09-05 17:55:19.776"
            DERIVED_DATES="0"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="cmp5"
            NAME="Disabled"
            PUBLICATION_DATE="2010-01-01 11:06:00.0"
            START_DATE="2010-01-01 11:06:00.0"
            STATUS_NAME="DISABLED"
            UPDATED_BY="Denys_M"
            UPDATED_DATE="2012-09-05 17:59:04.818"
            />
    <ACTIVITY
            ACTIVITY_ID="11005"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="eb12ee5b-e96f-4347-8f03-23b3fb391a30"
            NAME="Activity 1"
            OPT_IN="0"
            PUBLICATION_DATE="2010-01-01 11:06:00.0"
            START_DATE="2010-01-01 11:06:00.0"
            STATUS_NAME="DISABLED"
            TEST="0"
            CAMPAIGN_ID="10005"
            />
    <CAMPAIGN
            CAMPAIGN_ID="10006"
            CASINO_ID="81004"
            CASINO_NAME="playtech81004"
            CATEGORY_ID="ACQUISITION"
            CREATED_BY="Denys_M"
            CREATED_DATE="2012-09-05 17:55:19.776"
            DERIVED_DATES="0"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="cmp6"
            NAME="Paused"
            PUBLICATION_DATE="2012-08-29 13:41:00.0"
            START_DATE="2010-01-01 11:06:00.0"
            STATUS_NAME="PAUSED"
            UPDATED_BY="Denys_M"
            UPDATED_DATE="2012-09-05 17:59:04.818"
            />
    <ACTIVITY
            ACTIVITY_ID="11006"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="eb12ee5b-e96f-4347-8f03-23b3fb391a30"
            NAME="Activity 1"
            OPT_IN="0"
            PUBLICATION_DATE="2012-08-29 13:41:00.0"
            START_DATE="2010-01-01 11:06:00.0"
            STATUS_NAME="PAUSED"
            TEST="0"
            CAMPAIGN_ID="10006"
            />
    <CAMPAIGN
            CAMPAIGN_ID="10007"
            CASINO_ID="81004"
            CASINO_NAME="playtech81004"
            CATEGORY_ID="ACQUISITION"
            CREATED_BY="Denys_M"
            CREATED_DATE="2012-09-05 17:55:19.776"
            DERIVED_DATES="0"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="cmp7"
            NAME="Pending Approval"
            PUBLICATION_DATE="2012-08-29 13:41:00.0"
            START_DATE="2010-01-01 11:06:00.0"
            STATUS_NAME="PENDING_APPROVAL"
            UPDATED_BY="Denys_M"
            UPDATED_DATE="2012-09-05 17:59:04.818"
            />
    <ACTIVITY
            ACTIVITY_ID="11007"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="eb12ee5b-e96f-4347-8f03-23b3fb391a30"
            NAME="Activity 1"
            OPT_IN="0"
            PUBLICATION_DATE="2012-08-29 13:41:00.0"
            START_DATE="2010-01-01 11:06:00.0"
            STATUS_NAME="PENDING_APPROVAL"
            TEST="0"
            CAMPAIGN_ID="10007"
            />
</dataset>

=== kasheylm/qa_cm_1.0/target/test-classes/search/SearchByNameTest.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "dbunit-dataset.dtd">
<dataset>
    <CAMPAIGN
            CAMPAIGN_ID="10001"
            CASINO_ID="81004"
            CASINO_NAME="playtech81004"
            CATEGORY_ID="ACQUISITION"
            CREATED_BY="Denys_M"
            CREATED_DATE="2012-09-05 17:55:19.776"
            DERIVED_DATES="0"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="cmp1"
            NAME="SimpleName"
            PUBLICATION_DATE="2010-01-01 11:06:00.0"
            START_DATE="2010-01-01 11:06:00.0"
            STATUS_NAME="IN_DESIGN"
            UPDATED_BY="Denys_M"
            UPDATED_DATE="2012-09-05 17:59:04.818"
            />
    <ACTIVITY
            ACTIVITY_ID="11001"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="eb12ee5b-e96f-4347-8f03-23b3fb391a30"
            NAME="Activity 1"
            OPT_IN="0"
            PUBLICATION_DATE="2010-01-01 11:06:00.0"
            START_DATE="2010-01-01 11:06:00.0"
            STATUS_NAME="IN_DESIGN"
            TEST="0"
            CAMPAIGN_ID="10001"
            />
    <CAMPAIGN
            CAMPAIGN_ID="10002"
            CASINO_ID="81004"
            CASINO_NAME="playtech81004"
            CATEGORY_ID="ACQUISITION"
            CREATED_BY="Denys_M"
            CREATED_DATE="2012-09-05 17:55:19.776"
            DERIVED_DATES="0"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="cmp2"
            NAME="1234567890"
            PUBLICATION_DATE="2010-01-01 11:06:00.0"
            START_DATE="2010-01-01 11:06:00.0"
            STATUS_NAME="IN_DESIGN"
            UPDATED_BY="Denys_M"
            UPDATED_DATE="2012-09-05 17:59:04.818"
            />
    <ACTIVITY
            ACTIVITY_ID="11002"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="eb12ee5b-e96f-4347-8f03-23b3fb391a30"
            NAME="Activity 1"
            OPT_IN="0"
            PUBLICATION_DATE="2010-01-01 11:06:00.0"
            START_DATE="2010-01-01 11:06:00.0"
            STATUS_NAME="IN_DESIGN"
            TEST="0"
            CAMPAIGN_ID="10002"
            />
    <CAMPAIGN
            CAMPAIGN_ID="10003"
            CASINO_ID="81004"
            CASINO_NAME="playtech81004"
            CATEGORY_ID="ACQUISITION"
            CREATED_BY="Denys_M"
            CREATED_DATE="2012-09-05 17:55:19.776"
            DERIVED_DATES="0"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="cmp3"
            NAME="!@#$%^*()_+=-?.>/,`~"
            PUBLICATION_DATE="2010-01-01 11:06:00.0"
            START_DATE="2010-01-01 11:06:00.0"
            STATUS_NAME="IN_DESIGN"
            UPDATED_BY="Denys_M"
            UPDATED_DATE="2012-09-05 17:59:04.818"
            />
    <ACTIVITY
            ACTIVITY_ID="11003"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="eb12ee5b-e96f-4347-8f03-23b3fb391a30"
            NAME="Activity 1"
            OPT_IN="0"
            PUBLICATION_DATE="2010-01-01 11:06:00.0"
            START_DATE="2010-01-01 11:06:00.0"
            STATUS_NAME="IN_DESIGN"
            TEST="0"
            CAMPAIGN_ID="10003"
            />

    <CAMPAIGN
            CAMPAIGN_ID="10004"
            CASINO_ID="81004"
            CASINO_NAME="playtech81004"
            CATEGORY_ID="ACQUISITION"
            CREATED_BY="Denys_M"
            CREATED_DATE="2012-09-05 17:55:19.776"
            DERIVED_DATES="0"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="cmp4"
            NAME="&lt;script language='JavaScript'> alert('Добрый день') &lt;/script>"
            PUBLICATION_DATE="2010-01-01 11:06:00.0"
            START_DATE="2010-01-01 11:06:00.0"
            STATUS_NAME="IN_DESIGN"
            UPDATED_BY="Denys_M"
            UPDATED_DATE="2012-09-05 17:59:04.818"
            />
    <ACTIVITY
            ACTIVITY_ID="11004"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="eb12ee5b-e96f-4347-8f03-23b3fb391a30"
            NAME="Activity 1"
            OPT_IN="0"
            PUBLICATION_DATE="2010-01-01 11:06:00.0"
            START_DATE="2010-01-01 11:06:00.0"
            STATUS_NAME="IN_DESIGN"
            TEST="0"
            CAMPAIGN_ID="10004"
            />
    <CAMPAIGN
            CAMPAIGN_ID="10005"
            CASINO_ID="81004"
            CASINO_NAME="playtech81004"
            CATEGORY_ID="ACQUISITION"
            CREATED_BY="Denys_M"
            CREATED_DATE="2012-09-05 17:55:19.776"
            DERIVED_DATES="0"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="cmp5"
            NAME="asdddddddd!@#dqweasdadaasddddddddddddqweasdadaasddddddddddddqweasdadaasddddddddddddqweasdadaasdddddddddddd1234adadaasddddddddddddqweasdadaasddddddddddddqweasdadaasddddddddddddqweasdadaasddddddddddddqw"
            PUBLICATION_DATE="2010-01-01 11:06:00.0"
            START_DATE="2010-01-01 11:06:00.0"
            STATUS_NAME="IN_DESIGN"
            UPDATED_BY="Denys_M"
            UPDATED_DATE="2012-09-05 17:59:04.818"
            />
    <ACTIVITY
            ACTIVITY_ID="11005"
            END_DATE="2020-01-01 00:00:00.0"
            LABEL="eb12ee5b-e96f-4347-8f03-23b3fb391a30"
            NAME="Activity 1"
            OPT_IN="0"
            PUBLICATION_DATE="2010-01-01 11:06:00.0"
            START_DATE="2010-01-01 11:06:00.0"
            STATUS_NAME="IN_DESIGN"
            TEST="0"
            CAMPAIGN_ID="10005"
            />
</dataset>

=== kasheylm/qa_cm_1.0/src/test/resources/clean.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "dbunit-dataset.dtd">

<dataset>
    <ACTION_SET />
    <ACTION_CONFIG />
    <ACTION_CONFIG_DETAIL />
    <CAMPAIGN />
    <ACTIVITY />
    <PLAYER />
    <ACTION_RESULT />
    <ACTIVITY_TARGET_GROUP />
    <PLAYER_DISTRIBUTION />
    <LANGUAGE />
    <ACTIVITY_FILTER />
    <CRON_EXPRESSION />
    <EXCLUSION_DATE />
    <ACTIVITY_FREQUENCY />
    <ACTIVITY_PROPERTY />
    <CONDITION_SET />
    <CONDITION />
    <TAG />
    <COUNTRY />
    <COUNTY />
    <VALUE_DESCRIPTOR />
    <VALUE_GROUP />
    <LVALUE />
    <VALUE_PROVIDER />
    <VALUE_VALIDATOR />
    <VALUE_INPUT_TYPE />
    <OPERATOR />
</dataset>
